<?php
/**
 * VietShield Blocked IPs
 * 
 * This file contains the list of IPs to be blocked by the early blocker.
 * DO NOT EDIT THIS FILE MANUALLY - It is auto-generated by VietShield WAF.
 */

return [
    'exact' => [],
    'ranges' => [],
    'updated' => date('Y-m-d H:i:s')
];
