<?php
/**
 * VietShield Early Blocker
 * 
 * This file is loaded BEFORE WordPress to block malicious IPs immediately.
 * This provides maximum performance by blocking at the earliest possible stage.
 * 
 * DO NOT EDIT THIS FILE MANUALLY - It is auto-generated by VietShield WAF.
 */

// This file is loaded BEFORE WordPress via auto_prepend_file
// Get client IP
if (true) {
    $ip = '';
    if (!empty($_SERVER['HTTP_CF_CONNECTING_IP'])) {
        $ip = $_SERVER['HTTP_CF_CONNECTING_IP'];
    } elseif (!empty($_SERVER['HTTP_X_REAL_IP'])) {
        $ip = $_SERVER['HTTP_X_REAL_IP'];
    } elseif (!empty($_SERVER['HTTP_X_FORWARDED_FOR'])) {
        $ip = explode(',', $_SERVER['HTTP_X_FORWARDED_FOR'])[0];
        $ip = trim($ip);
    } else {
        $ip = $_SERVER['REMOTE_ADDR'] ?? '';
    }
    
    // Validate IP
    if (!filter_var($ip, FILTER_VALIDATE_IP)) {
        return; // Invalid IP, let WordPress handle it
    }
    
    // Load blocked IPs list
    $block_file = __DIR__ . '/vietshield-blocked-ips.php';
    if (file_exists($block_file)) {
        $blocked_ips = include $block_file;
        
        if (is_array($blocked_ips) && !empty($blocked_ips)) {
            // Check exact IP match
            if (isset($blocked_ips['exact'][$ip])) {
                vietshield_block_request($ip, $blocked_ips['exact'][$ip]);
            }
            
            // Check CIDR ranges
            if (!empty($blocked_ips['ranges'])) {
                foreach ($blocked_ips['ranges'] as $range => $reason) {
                    if (vietshield_ip_in_range($ip, $range)) {
                        vietshield_block_request($ip, $reason);
                    }
                }
            }
        }
    }
}

/**
 * Block request immediately
 */
function vietshield_block_request($ip, $reason = 'Blocked by VietShield WAF') {
    // Log to file for debugging (optional)
    // error_log(sprintf('VietShield: Blocked IP %s - %s', $ip, $reason));
    
    // Send 403 response
    http_response_code(403);
    header('Content-Type: text/html; charset=UTF-8');
    
    $block_id = substr(md5($ip . time()), 0, 12);
    $timestamp = date('Y-m-d H:i:s');
    
    echo '<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Access Denied</title>
    <style>
        body { font-family: Arial, sans-serif; text-align: center; padding: 50px; background: #f5f5f5; }
        .container { max-width: 600px; margin: 0 auto; background: white; padding: 30px; border-radius: 5px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        h1 { color: #d32f2f; }
        .block-id { color: #666; font-size: 12px; margin-top: 20px; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Access Denied</h1>
        <p>Your request has been blocked for security reasons.</p>
        <p class="block-id">Block ID: ' . htmlspecialchars($block_id) . '<br>Time: ' . htmlspecialchars($timestamp) . '</p>
    </div>
</body>
</html>';
    
    exit;
}

/**
 * Check if IP is in CIDR range
 */
function vietshield_ip_in_range($ip, $range) {
    if (strpos($range, '/') === false) {
        return $ip === $range;
    }
    
    list($subnet, $bits) = explode('/', $range);
    
    // IPv4
    if (filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV4)) {
        $ip_long = ip2long($ip);
        $subnet_long = ip2long($subnet);
        $mask = -1 << (32 - (int) $bits);
        $subnet_long &= $mask;
        return ($ip_long & $mask) === $subnet_long;
    }
    
    // IPv6 (simplified check)
    if (filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6)) {
        // For IPv6, we'll do a simple prefix match
        $ip_hex = bin2hex(inet_pton($ip));
        $subnet_hex = bin2hex(inet_pton($subnet));
        $prefix_len = (int) $bits / 4; // Each hex char is 4 bits
        return substr($ip_hex, 0, $prefix_len) === substr($subnet_hex, 0, $prefix_len);
    }
    
    return false;
}
